import Head from 'next/head';
import ArticleCard from 'components/article-card';
import { Card, CardBody, Typography } from '@material-tailwind/react';
import { gql } from '@apollo/client';
import client from 'utils/apollo-client';
import { NAVBAR_FIELDS, parseNavbarFields } from 'components/navbar';
import { flatten } from 'utils/graphql-utils';
import { ArticlePreview } from 'additional';

interface SportPath {
  attributes: {
    slug: string
  }
}
interface SportProps {
  sport: {
    name: string
    topics: {
      title: string
      content: string
    }[]
    articles: ArticlePreview[]
  }
}

const CoverArticle = ({ article }: { article: ArticlePreview }) => {
  if (!article) {
    return null;
  }
  return (
    <ArticleCard className="w-full h-64" title={article.title} cover={article.cover}/>
  )
}

export default function Sport({ sport }: SportProps) {
  return (
    <>
      <Head>
        <title>DL Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-16 md:px-20">
        <Typography as="h1" variant="lead" className="mt-4 mb-6 text-3xl text-center md:text-left">
          {sport.name}
        </Typography>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <CoverArticle article={sport.articles?.[0]}/>

          <div className="w-full md:h-64 md:col-span-2">
            <div className="h-full grid grid-cols-1 lg:grid-cols-2 gap-y-4 gap-x-12 lg:overflow-scroll">
              {sport.articles.slice(1).map(article => (
                <Card key={article.title} color="grey">
                  <CardBody className="max-w-full max-h-full">
                    <Typography as="h5" variant="small" className="mb-2 font-bold">
                      {article.title}
                    </Typography>
                  </CardBody>
                </Card>
              ))}
            </div>
          </div>

          {sport.topics.map(topic => (
            <Card key={topic.title} className="w-full h-64 px-8 py-2 overflow-y-scroll topic-card">
              <Typography as="h3" variant="lead" className="text-center font-bold mb-2">
                {topic.title}
              </Typography>
              <div dangerouslySetInnerHTML={{ __html: topic.content }}/>
            </Card>
          ))}
        </div>
      </div>
    </>
  )
}

export async function getStaticPaths() {
  const { data } = await client.query({
    query: gql`
        query AllSports {
            sports {
                data {
                    attributes {
                        slug
                    }
                }
            }
        }
    `
  })
  const paths = data.sports.data.map((sport: SportPath) => ({ params: { slug: sport.attributes.slug } }));
  return { paths, fallback: 'blocking' };
}

export async function getStaticProps({ params }: { params: { slug: string } }) {
  const { data } = await client.query({
    query: gql`
        ${NAVBAR_FIELDS}
        query Sport($slug: String!) {
            sport(slug: $slug) {
                data {
                    attributes {
                        name
                        topics {
                            title
                            content
                        }
                        articles(pagination: {page: 1, pageSize: 5}) {
                            data {
                                attributes {
                                    title
                                    cover {
                                        data {
                                            attributes {
                                                url
                                                alternativeText
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            ...NavbarFields
        }
    `,
    variables: {
      slug: params.slug
    }
  })

  const flattened = flatten(data.sport);
  flattened.articles.forEach((article: ArticlePreview) => {
    article.cover.url = process.env.STRAPI_URL + article.cover.url
  });

  return {
    props: {
      sport: flattened,
      navbar: parseNavbarFields(data),
    }
  };
}
