import client from "../../apollo-client";
import { gql } from "@apollo/client";
import Head from "next/head";
import { getScripts } from "../../utils/script-helpers";
import Script from "next/script";

export default function Article({ article }) {
  const externalScripts = getScripts(article.body);

  return (
    <div className="py-0 px-8">
      <Head>
        <title>DL Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen	w-3/4 mx-auto py-14 px-0 items-center">
        <h1 className="m-0 my-16 text-6xl text-center">{article.title}</h1>

        <div>
          <div dangerouslySetInnerHTML={{ __html: article.body }} />
          {externalScripts.map((script) => (
            <Script key={script} src={script} strategy="lazyOnload"/>
          ))}
        </div>
      </main>
    </div>
  )
}

export async function getStaticPaths() {
  const { data } = await client.query({
    query: gql`
        query Articles {
            articles {
                data {
                    attributes {
                        slug
                    }
                }
            }
        }
    `
  })

  const paths = data.articles.data.map((article) => ({
    params: { slug: article.attributes.slug }
  }))
  return { paths, fallback: 'blocking' };
}

export async function getStaticProps({ params }) {
  const { data } = await client.query({
    query: gql`
        query Article {
            article(id: 4) {
                data {
                    attributes {
                        title
                        body
                    }
                }
            }
        }
    `,
  });

  return {
    props: {
      article: data.article.data.attributes,
    },
  };
}
