import Head from 'next/head';

export default function Category() {
  return (
    <>
      <Head>
        <title>DL Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-20 md:px-20">
        <h1 className="mt-4 mb-6 text-3xl text-center md:text-left">MLB</h1>
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          <div className="w-full h-56 bg-neutral-500 order-first"></div>
          <div className="w-full h-56 bg-neutral-500 order-2"></div>
          <div className="w-full h-56 bg-neutral-500 order-3"></div>
          <div className="w-full h-56 bg-neutral-500 order-4"></div>
          <div className="w-full h-56 bg-neutral-200 md:col-span-2 order-last md:order-1">
            <div className="h-full md:p-4 grid grid-cols-1 lg:grid-cols-2 gap-y-4 gap-x-12">
              <div className="w-full h-full bg-neutral-500"></div>
              <div className="w-full h-full bg-neutral-500"></div>
              <div className="w-full h-full bg-neutral-500"></div>
              <div className="w-full h-full bg-neutral-500"></div>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
