import client from "utils/apollo-client";
import { gql } from "@apollo/client";
import Head from "next/head";
import { getScripts } from "utils/script-helpers";
import Script from "next/script";
import { NAVBAR_FRAGMENT } from '../../utils/graphql-fragments';
import { flatten } from '../../utils/graphql-utils';
import { Typography } from '@material-tailwind/react';
import Image from 'next/image';
import AuthorCard from '../../components/author-card';
import { Article } from 'additional';

interface ArticlePageProps {
  article: Partial<Article>
}

export default function ArticlePage({ article }: ArticlePageProps ) {
  const externalScripts = article.body ? getScripts(article.body) : [];

  return (
    <>
      <Head>
        <title>DL Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="md:w-3/4 xl:w-2/3 mx-auto py-14 items-center">
        <Typography as="h1" className="mb-8 text-center text-2xl">
          {article.title}
        </Typography>

        <div className="flex justify-center">
          {article.cover?.url &&
            <Image
              src={article.cover.url}
              alt={article.cover.alternativeText}
              layout="intrinsic"
              width="1000"
              height="400"
              objectFit="cover"
              priority={true}
            />
          }
        </div>

        <div className="py-8">
          <Typography as="div">
            <div dangerouslySetInnerHTML={{ __html: article.body ?? "" }} />
            {externalScripts.map((script) => (
              <Script key={script} src={script} strategy="lazyOnload"/>
            ))}
          </Typography>
        </div>

        {article.author && <AuthorCard author={article.author}/>}
      </div>
    </>
  )
}

export async function getStaticPaths() {
  const { data } = await client.query({
    query: gql`
        query Articles {
            articles {
                data {
                    attributes {
                        slug
                    }
                }
            }
        }
    `
  })

  const paths = data.articles.data.map((article: { attributes: { slug: string } }) => ({
    params: { slug: article.attributes.slug }
  }))
  return { paths, fallback: 'blocking' };
}

export async function getStaticProps({ params }: { params: { slug: string } }) {
  const { data } = await client.query({
    query: gql`
        ${NAVBAR_FRAGMENT}
        query Article($slug: String!) {
            article(slug: $slug) {
                data {
                    attributes {
                        title
                        slug
                        body
                        cover {
                            data {
                                attributes {
                                    url
                                    alternativeText
                                }
                            }
                        }
                        author {
                            data {
                                attributes {
                                    name
                                    email
                                    avatar {
                                        data {
                                            attributes {
                                                url
                                                alternativeText
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            ...Navbar
        }
    `,
    variables: {
      slug: params.slug
    }
  });


  const flattenedArticle = flatten(data.article);
  if (flattenedArticle.cover.url) {
    flattenedArticle.cover.url = process.env.STRAPI_URL + flattenedArticle.cover.url;
  }
  if (flattenedArticle.author.avatar.url) {
    flattenedArticle.author.avatar.url = process.env.STRAPI_URL + flattenedArticle.author.avatar.url;
  }

  return {
    props: {
      article: flattenedArticle,
      navbar: {
        sports: flatten(data.sports)
      },
    },
  };
}
