import { gql } from "@apollo/client";
import client from "../utils/apollo-client";
import Head from 'next/head'

export default function Home({ article }) {
  return (
    <div className="py-0 px-8">
      <Head>
        <title>DL Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="min-h-screen	py-20 px-0 flex flex-1 flex-col justify-center items-center">
        <h1 className="m-0 mb-8 text-6xl text-center">{article.attributes.title}</h1>

        <div className="mt-8">
          <div dangerouslySetInnerHTML={{ __html: article.attributes.body }} />
        </div>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
        query Article {
            article(id: 4) {
                data {
                    id
                    attributes {
                        title
                        body
                    }
                }
            }
        }
    `,
  });

  return {
    props: {
      article: data.article.data,
    },
  };
}
