import Head from 'next/head'
import ArticleCard from 'components/article-card';
import client from 'utils/apollo-client';
import { gql } from '@apollo/client';
import { NAVBAR_FRAGMENT } from 'utils/graphql-fragments';
import { flatten } from 'utils/graphql-utils';
import { Article } from 'additional';

interface HomePageProps {
  articles: Partial<Article>[]
}

export default function HomePage({ articles }: HomePageProps) {
  return (
    <>
      <Head>
        <title>DL Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full py-16 md:pt-28 md:px-10 flex flex-col md:flex-row gap-16 justify-center items-center">
        <ArticleCard className="w-screen md:w-[490px] h-[490px]" size="lg" article={articles?.[0]}/>
        <div className="flex flex-col items-center">
          <h2 className="pb-6 text-3xl">Latest News</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {articles.slice(1).map((article, index) => (
              <ArticleCard key={article.title ?? index} className="w-48 h-48" size="sm" article={article}/>
            ))}
          </div>
        </div>
      </div>

      <div className="w-screen h-[50px] mb-10 bg-grey-200 flex flow-row gap-10 justify-center">
        {[0, 1, 2, 3, 4].map((i) => (
          <div key={i} className="w-6 h-6 my-auto bg-grey-500"></div>
        ))}
      </div>
    </>
  )
}

export async function getStaticProps() {
  const { data } = await client.query({
    query: gql`
        ${NAVBAR_FRAGMENT}
        query HomePage {
            articles(pagination: {page: 1, pageSize: 5}, sort: "publishedAt:desc") {
                data {
                    attributes {
                        title
                        cover {
                            data {
                                attributes {
                                    url
                                    alternativeText
                                }
                            }
                        }
                    }
                }
            }
            ...Navbar
        }
    `
  });

  const flattenedArticles = flatten(data.articles);
  flattenedArticles.forEach((article: Article) => {
    if (article.cover.url) {
      article.cover.url = process.env.STRAPI_URL + article.cover.url
    }
  });

  return {
    props: {
      articles: flattenedArticles,
      navbar: {
        sports: flatten(data.sports)
      }
    }
  }
}
