import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>DL Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="h-full py-16 md:pt-28 md:px-10 flex flex-col md:flex-row gap-16 justify-center items-center">
        <div className="text-center">
          <div className="w-screen md:w-[490px] h-[490px] bg-neutral-500"></div>
          <h5 className="text-2xl">Lorem ipsum</h5>
        </div>
        <div className="flex flex-col items-center">
          <h2 className="pb-6 text-3xl">Latest News</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {[0, 1, 2, 3].map((i) => (
              <div key={i} className="text-center">
                <div className="w-48 h-48 bg-neutral-500"></div>
                <h5>Lorem ipsum</h5>
              </div>
            ))}
          </div>
        </div>
      </div>

      <div className="w-screen h-[50px] mb-10 bg-neutral-200 flex flow-row gap-10 justify-center">
        {[0, 1, 2, 3, 4].map((i) => (
          <div key={i} className="w-6 h-6 my-auto bg-neutral-500"></div>
        ))}
      </div>
    </>
  )
}
