import Head from 'next/head';

export default function Podcast() {
  return (
    <>
      <Head>
        <title>DL Sports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="my-20 md:px-48 w-screen">
        <h1 className="mt-4 mb-10 md:mb-6 text-3xl text-center">&quot;On the DL&quot; Podcast</h1>
        <div className="flex flex-col md:flex-row gap-16 md:gap-24 justify-between">
          <div className="w-full lg:w-[450px] max-w-screen h-[500px] bg-neutral-500"></div>
          <div className="w-full lg:w-[450px] max-w-screen h-[500px] bg-neutral-200">
            <div className="flex flex-col gap-6">
              <h3 className="text-center text-xl">Other Episodes</h3>
              {[0,1,2,3,4].map((i) => (
                <div key={i} className="w-full h-16 bg-neutral-500"></div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
